language: python
dist: bionic
python:
  - "3.7"

script:
  - python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: $PYPI_USER
  password: $PYPI_PW
  on:
    tags: true
